version: "3"
services:
  hn-service:
    #image: hacker_news_hn-service:latest
    build:
      context: ./target/docker/stage
    container_name: hacker-news
    ports:
      - 8095:8090
    environment:
      MONGO_HOST: mongo1
      VOTE_WEIGHT: 1
      CREATION_TIME_WEIGHT: 1
    depends_on:
      - mongo1
    networks:
      - mongo

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.0-xenial
    expose:
      - 27017
    ports:
      - 27011:27017
    restart: always
    networks:
      - mongo
networks:
  mongo:
    driver: bridge