version: "3"
services:
  hn-service:
    build:
      context: ./target/docker/stage
    container_name: hacker-news
    ports:
      - 8095:8090
    environment:
      MONGO_HOST: mongo1
#    links:
#      - mongo1
    depends_on:
      - mongo1
    networks:
      - mongo

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.0-xenial
    expose:
      - 27017
    ports:
      - 27011:27017
    restart: always
    networks:
      - mongo
    #entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
networks:
  mongo:
    driver: bridge